/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tictactoelib */

#ifndef _Included_tictactoelib
#define _Included_tictactoelib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tictactoelib
 * Method:    makeMoveJNI
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tictactoelib_makeMoveJNI
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     tictactoelib
 * Method:    getBoardStateJNI
 * Signature: ()[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_tictactoelib_getBoardStateJNI
  (JNIEnv *, jclass);

/*
 * Class:     tictactoelib
 * Method:    resetGameJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tictactoelib_resetGameJNI
  (JNIEnv *, jclass);

/*
 * Class:     tictactoelib
 * Method:    getCurrentPlayerJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tictactoelib_getCurrentPlayerJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
